// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWMUTONksvIoelARjGgfdlQ_VRsnplEg',
    appId: '1:706830974756:web:650f9fe834ee2eaa4ffdb1',
    messagingSenderId: '706830974756',
    projectId: 'mynotess-b1149',
    authDomain: 'mynotess-b1149.firebaseapp.com',
    storageBucket: 'mynotess-b1149.appspot.com',
    measurementId: 'G-325EERTQB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2q3asRclbBOWla-6MvaOrFYOHxwXEtpU',
    appId: '1:706830974756:android:8875c7227e6e3bd64ffdb1',
    messagingSenderId: '706830974756',
    projectId: 'mynotess-b1149',
    storageBucket: 'mynotess-b1149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHyBcDVhsX2bKHZB3AyazkBrC1MyXN7k',
    appId: '1:706830974756:ios:5fcb6e24be79249d4ffdb1',
    messagingSenderId: '706830974756',
    projectId: 'mynotess-b1149',
    storageBucket: 'mynotess-b1149.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );
}
